import type { Metadata } from "next";
import { cn } from "cn";
import { Space_Grotesk, Newsreader, Inter } from "next/font/google";

import { ThemeProvider } from "@/components/layout/theme-provider";
import { Navbar } from "@/components/layout/navbar";

import "./globals.css";

const spaceGroteskHeading = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-heading",
});

const newsreaderSerif = Newsreader({
  subsets: ["latin"],
  variable: "--font-serif",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="fr-MA"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        newsreaderSerif.variable,
        spaceGroteskHeading.variable,
        inter.variable,
      )}
      suppressHydrationWarning
    >
      <body className="relative min-h-screen bg-background">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div id="scroll-sentinel" className="absolute top-0 h-px w-full" />

          <div className="relative">
            <div
              aria-hidden
              className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-125 bg-[radial-gradient(ellipse_90%_55%_at_50%_35%,color-mix(in_oklch,var(--primary)_25%,transparent),transparent_72%)] sm:h-140 md:h-175"
            />

            <Navbar />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
